<?php foreach($array_obj as $obj):?>
    <form class=" <?php if($obj->getRunning()){ echo "invisible";} ?> col-4 text-center <?php echo strcmp($obj->getNameObj(),"Pauza")==0?" ml-auto mr-5":""?>" action="/" method="post">
        <button type="submit" name="<?php echo objPropertyName_to_varString($obj)?>" class="btn btn-<?php echo strcmp($obj->getNameObj(),"Pauza")==0?"warning ":"success"?>  mt-5  ">
            <i class="fa fa-<?php echo strcmp($obj->getNameObj(),"Pauza")==0?"pause ":"play"?> fa-lg"></i> <?php echo $obj->getNameObj() ?> 
        </button>
    </form>
<?php endforeach;  ?> 